version: '3.8'

services:
  n8n:
    build: .
    image: n8n-puppeteer:latest
    container_name: n8n-puppeteer
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=UTC
      - WEBHOOK_TUNNEL=false
    volumes:
      - ./n8n-data:/home/node/.n8n
    shm_size: 1gb
    # Uncomment if Chrome sandbox fails:
    # privileged: true
